### ISSUE TITLE
GPM and XPM graphs

### ISSUE THREAD

**Issue by icheyne** [d2rm/d2rm#10]
It would be good to see GPM and XPM graphs in d2rm. Dotabuff only offers XPM to regular users.

Here is a screenshot of what they look like for paid users.
![dotabuffcharts](https://cloud.githubusercontent.com/assets/389366/6099333/37a2aaca-afed-11e4-8692-2cdbfa57c41f.png)

**Comment by pyarmak** [comment]
Oh that's actually already available. You just need to parse the replay of the match for those then a "Graphs" tab will become available on the match page. There you will have 4 graphs available to you: advantage (xp, gold), last hits, gold, and xp.

**Comment by icheyne** [comment]
I will. :+1:
