### ISSUE TITLE
Windows X64 Support

### ISSUE THREAD

**Issue by XavierCHN** [d2rm/d2rm#17]

**Comment by pyarmak** [comment]
It's already supported. Granted there's no x64 binary but you can still use the 32bit release on x64 systems. I was told that x64 systems still need a 32bit version of Java installed to run the parser. This is something I will look into when I release the next major version seeing as I have med school interviews starting next week, I will be unable to release anything until after March 14th.

Eventually I want to upgrade all the dependencies and node-webkit to the latest version which has native x64 windows support but that would take a lot of work so it will depend on donations and time I get.
