### ISSUE TITLE
Crashes when Synchronizing / After Startup

### ISSUE THREAD

**Issue by Shazam-** [d2rm/d2rm#2]
Looks like I'm a bug magnet haha

So i decided to use this to track some pro player replays

Arteezy:
.../Arteezy

S4:
.../76561198001497299

and Eternal Envy:
.../76561198003541947

And at first it worked really well, then i hit synchronize and it crashed. And now it crashes after about 5 seconds, like it did last time.

Exception log:
http://pastebin.com/SzGJGFVL

Dota log:
2014-12-28T05:28:43.035Z - info: [BACKEND] Fetching players' histories
2014-12-28T05:28:43.038Z - info: [BACKEND] Parsing unparsed matches
2014-12-28T05:28:43.038Z - info: Scraping tracked player information

**Comment by pyarmak** [comment]
I was away for holidays but now that I'm back I'll look into it and push a fix in the next couple of days.
From taking a brief look at the log it looks like an interesting error. I'll try to recreate it and see how it goes.

Thank you for taking the time to post these bug reports. It really helps!

**Comment by pyarmak** [comment]
This bug has led me down a rabbit hole... When I fix one bug, another one pops up. I'll publish a new release once I'm sure that these bugs have been quashed. For now stick to tracking one player (I know that kind of sucks).

**Comment by stuki** [comment]
I'm having the same issue of crashing when starting

http://pastebin.com/E6ZWfgdU

https://gfycat.com/SameCostlyHarvestmouse

**Comment by pyarmak** [comment]
stuki your error is quite different than the one experienced by Shazam-.
Somehow your ursa module (which is installed with the program) is missing. I have no idea how that could have happened but try reinstalling the program and see if that helps.

On another note, I'm wondering if v0.1.0 fixed your issue Shazam-

**Comment by stuki** [comment]
I have reinstalled with no luck. Or actually I did not remove the folder because I did not want to lose any data. I should have mentioned that I got it up and running the first time, and added an account and all that. But after that it started crashing. It also refused to load any matches before it started crashing, but now I see a glimpse of the matches before I goes away. I'll try reinstalling completely now and come back.

**Comment by pyarmak** [comment]
Ok perfect that error I can work with.
I'll look into it. I just have a couple or errands to run right now but I should have an answer to it by tonight.

**Comment by pyarmak** [comment]
I have made some changes which will hopefully fix this issue in my development build  but honestly I've made so many changes for the next release that some things may have gotten lost in the shuffle so I'll pick it up once the new version is up.
The release should be up within a couple of days. I'm just finishing it up now. It's going to be a major release (0.2.0) which will include the source code!

**Comment by pyarmak** [comment]
I am closing all issues as I have tried addressing them in 0.2.0
