### ISSUE TITLE
Program crashes upon hitting download replay

### ISSUE THREAD

**Issue by GrandPyromania** [d2rm/d2rm#3]
Dota log: http://pastebin.com/cSpvtZ7L
Exception log: http://pastebin.com/cM5wYDiA

**Comment by pyarmak** [comment]
Hmm well at least it is finding the module... 
This is the ursa module I'm talking about:
https://github.com/NodePrime/ursa
If you want to try compiling it yourself you can do so using nw-gyp with --target=0.8.6 (you can't use the default node-gyp). Here is a link to nw-gyp:
https://github.com/rogerwang/nw-gyp
Then you can replace the compiled native module in:
C:\\Users\\Excalibur\\AppData\\Roaming\\D2RM\\app\\node_modules\\steam\\node_modules\\ursa\\bin\\ursaNative.node

**Comment by GrandPyromania** [comment]
Sorry, I have no idea how to compile code or anything, so I'm afraid that's slightly out my skill set :p 

Anyway, I'm running this on a laptop, here's my dxdiag:
http://pastebin.com/Su2jZJLX

**Comment by pyarmak** [comment]
I'm looking into this but I am holding off on pushing any updates until I complete my next major release (0.2.0) which should be ready within a couple of days.

**Comment by pyarmak** [comment]
I am closing all issues as I have tried addressing them in 0.2.0
