### ISSUE TITLE
If settings not configured properly, the error message swirls uncontrollably

### ISSUE THREAD

**Issue by icheyne** [d2rm/d2rm#4]
1. Install d2rm.
2. Configure nothing
3. Synchronise

Error messages flicker very quickly.

**Comment by pyarmak** [comment]
Thank you for the report.
I fixed the issue in my development build. It will be included with my upcoming release.
The release should be up within a couple of days. I'm just finishing it up now. It's going to be a major release (0.2.0) which will include the source code!

**Comment by pyarmak** [comment]
I am closing all issues as I have tried addressing them in 0.2.0
