### ISSUE TITLE
Getting DataTables error message when opening match history

### ISSUE THREAD

**Issue by stuki** [d2rm/d2rm#6]
It still displays the matches, but for every page the error pops up.

http://i.imgur.com/FbQHNmP.png

**Comment by pyarmak** [comment]
Thank you for the report. I know what's causing it. It doesn't take into account the fact that your steam and replay paths can be not set thus making it unable to tell the replay availability. 
I will add a check for this in my next release.

**Comment by pyarmak** [comment]
Should be fixed in v0.2.1
