### ISSUE TITLE
Crashes when selecting "Track Steam Account"

### ISSUE THREAD

**Issue by stuki** [d2rm/d2rm#7]
```{"date":"Wed Jan 28 2015 22:03:38 GMT+0200 (FLE Standard Time)","process":{"pid":12552,"uid":null,"gid":null,"cwd":"C:\\Users\\os\\AppData\\Roaming\\D2RM\\app","execPath":"C:\\Users\\os\\AppData\\Roaming\\D2RM\\node-webkit\\nw.exe","version":"v0.10.22","argv":["node","C:\\Users\\os\\AppData\\Roaming\\D2RM\\app\\js\\node-main.js"],"memoryUsage":{"rss":120242176,"heapTotal":53900032,"heapUsed":35886048}},"os":{"loadavg":[0,0,0],"uptime":1350661.4135946},"trace":[{"column":32,"file":"module.js","function":"Module.load","line":359,"method":"load","native":false},{"column":12,"file":"module.js","function":"Function.Module._load","line":315,"method":"Module._load","native":false},{"column":17,"file":"module.js","function":"Module.require","line":367,"method":"require","native":false},{"column":17,"file":"module.js","function":"require","line":383,"method":null,"native":false},{"column":18,"file":"C:\\Users\\os\\AppData\\Roaming\\D2RM\\app\\node_modules\\steam\\node_modules\\ursa\\lib\\ursa.js","function":"Object.eval","line":18,"method":"eval","native":false},{"column":26,"file":"module.js","function":"Module._compile","line":459,"method":"_compile","native":false},{"column":10,"file":"module.js","function":"Object.Module._extensions..js","line":477,"method":"Module._extensions..js","native":false},{"column":32,"file":"module.js","function":"Module.load","line":359,"method":"load","native":false},{"column":12,"file":"module.js","function":"Function.Module._load","line":315,"method":"Module._load","native":false},{"column":17,"file":"module.js","function":"Module.require","line":367,"method":"require","native":false},{"column":17,"file":"module.js","function":"require","line":383,"method":null,"native":false}],"stack":["Error: The specified module could not be found.\r","C:\\Users\\os\\AppData\\Roaming\\D2RM\\app\\node_modules\\steam\\node_modules\\ursa\\bin\\ursaNative.node","    at Module.load (module.js:359:32)","    at Function.Module._load (module.js:315:12)","    at Module.require (module.js:367:17)","    at require (module.js:383:17)","    at Object.eval (C:\\Users\\os\\AppData\\Roaming\\D2RM\\app\\node_modules\\steam\\node_modules\\ursa\\lib\\ursa.js:18:18)","    at Module._compile (module.js:459:26)","    at Object.Module._extensions..js (module.js:477:10)","    at Module.load (module.js:359:32)","    at Function.Module._load (module.js:315:12)","    at Module.require (module.js:367:17)","    at require (module.js:383:17)"],"level":"error","message":"uncaughtException: The specified module could not be found.\r\nC:\\Users\\os\\AppData\\Roaming\\D2RM\\app\\node_modules\\steam\\node_modules\\ursa\\bin\\ursaNative.node","timestamp":"2015-01-28T20:03:38.370Z"}```

nothing in dota.log

**Comment by pyarmak** [comment]
It's the same ursa node_module bug from before. Still no clue what's causing it...
Can you just confirm real quick that the following file exists on your system:
```
C:\\Users\\os\\AppData\\Roaming\\D2RM\\app\\node_modules\\steam\\node_modules\\ursa\\bin\\ursaNative.node
```
I will ask for some help on the ursa repo when I have the time.

**Comment by stuki** [comment]
It exists and is in the right folder.
On 31.1.2015 10:37:27, Pavel Yarmak <notifications@github.com> wrote:
It's the same ursa node_module bug from before. Still no clue what's causing it...
Can you just confirm real quick that the following file exists on your system:
C:\\Users\\os\\AppData\\Roaming\\D2RM\\app\\node_modules\\steam\\node_modules\\ursa\\bin\\ursaNative.node
I will ask for some help on the ursa repo when I have the time.
&mdash;

**Comment by pyarmak** [comment]
Ok I seem to have found a computer that experiences the same issue (I commandeered my brother's computer).
I can now start looking into this.

**Comment by pyarmak** [comment]
Ok a quick and dirty test shows that installing OpenSSL on this system avoids this problem (http://slproweb.com/download/Win32OpenSSL_Light-1_0_1L.exe and the related C++ redistributable http://www.microsoft.com/downloads/details.aspx?familyid=9B2DA534-3E03-4391-8A4D-074B9F2BC1BF). 
I will investigate further as to why that is the case. My suspicion is that nw-gyp is dynamically linking or something.

**Comment by pyarmak** [comment]
Well that didn't take long. I solved the issue (there's no changes to commit as it is part of the build process). 
An updated binary (v0.2.1) will be up by tomorrow.
