### ISSUE TITLE
[non-issue] compiling the source

### ISSUE THREAD

**Issue by eloc574** [d2rm/d2rm#8]
just wondering how to compile from master on linux

**Comment by pyarmak** [comment]
Well it would take a while to explain fully (which I don't currently have time for) but I'll give you the main steps to get your started. Feel free to ask for clarifications and I'll respond as I can.

I'll assume you checked out the source and all that jazz. 
You will need nw-gyp installed (I will assume globally) which you can do with: ```npm install -g nw-gyp```
You want to run ```npm install``` in the root directory.
Then you want to go into your newly created node_modules folder and rebuild the following modules using nw-gyp: node-dota2/node_modules/protobuf
node-steam/node_modules/protobuf
node-steam/node_modules/ursa
node-steam/node_modules/ref
(you should be able to only build protobuf once and use it for both).
to do that you need to be in the root of the module directory and run ```nw-gyp rebuild --target=0.8.6```
An extra step is needed for ursa which is to move the built .node file from build/release to the bin folder (or you should be able to just remove the bin folder and then node's require will find the correct build).
Once you have all that done, you can then go back to the root and run any of the grunt commands (e.g. ```grunt run```)
There are more steps needed to package a release and this isn't even touching on building the parser submodule but these steps should let you get up and running.

**Comment by pyarmak** [comment]
I am going to lock this issue. If you have trouble with my instructions or any further questions, please feel free to post another comment.
