### ISSUE TITLE
Still crashing on sync

### ISSUE THREAD

**Issue by icheyne** [d2rm/d2rm#9]
d2rm still crashes while syncing. I can send you debug information if you want to fix this.

**Comment by pyarmak** [comment]
I will give it a shot! Lay em on me haha

**Comment by icheyne** [comment]
How can I generate the debug info you need?

We can talk on Skype or Steam or something if you like.

**Comment by pyarmak** [comment]
There are 2 log files automatically generated in ```C:\Users\<USERNAME>\AppData\Local\D2RM```.
Post exceptions.log and dota.log here for me. Thanks.

**Comment by Feralio** [comment]
Also adding to this issue; as i have it also.

The log files:
https://dl.dropboxusercontent.com/u/26132659/dota.log
https://dl.dropboxusercontent.com/u/26132659/exceptions.log

**Comment by pyarmak** [comment]
Oh wow this is a first. Welcome to the the most useless stack trace error: 
```Error: no errorG:\\D2RM\\app\\node_modules\\steam\\node_modules\\ursa\\bin\\ursaNative.node```
But other crashes are similar to this issue.
I'm going to release a hotfix for one of the error I already fixed by end of day if I can't find the other error by then.

**Comment by pyarmak** [comment]
New release is up (v0.2.2). Please test it out and let me know if any bugs are found.

**Comment by pyarmak** [comment]
Ok so I found some lingering issues. I will be releasing v0.2.3 soon.

**Comment by icheyne** [comment]
Sorry for the delay:

http://cheyne.net/tmp/exceptions.log
http://cheyne.net/tmp/dota.log

**Comment by pyarmak** [comment]
Ok I uploaded v0.2.3
Give that a shot and let me know how it goes.

**Comment by icheyne** [comment]
It works! First time since first release. Thanks mate. Looks good. How hard is it to implement gold graphs?

**Comment by Feralio** [comment]
Do you want me to create a new thread or continue within this one?

**Comment by pyarmak** [comment]
Awesome! Glad to hear it. 
Thank you for your time guys. 
I'll aim to add some more graphs for my next release (v0.3.0).
I may also have a surprise or two up my sleeve ;-)

**Comment by icheyne** [comment]
:-) Looking forward to Net Worth graphs. They are the only reason I buy Dotabuff Plus.

**Comment by pyarmak** [comment]
Actually, could you open a new "issue" ticket on here and like post a screenshot of what those graphs look like with a little description for me? 
I kind of want something to work off of.

**Comment by icheyne** [comment]
[Done](https://github.com/d2rm/d2rm/issues/10)
